### ISSUE TITLE
Does not appear in LV2018 menus

### ISSUE THREAD

**Issue by mili-tar** [NeosoftTechnologiesInc/LV-WinSCP#3]
I have installed DMQH, Improved Error Dialog and LV-WinSCP.
I see them in vi.lib folder.
I cannot find them in LV2018 palettes - nor can VIPM.

![2023-11-07_17-19-31](https://github.com/NeosoftTechnologiesInc/LV-WinSCP/assets/46570316/e3a9eb55-a045-4d2c-aa70-080697b3e03d)

**Comment by CyGaNeo** [comment]
Definitely a VIPM issue I'd say.
I know it works well out of the box for many versions.
Did you try installing it by launching VIPM as administrator? LabVIEW will inherit the rights and maybe few more things will happen and make it work. Keep me posted!
